name: Hello World Workflow
on:
  push:
    branches: ["master", "main"]
jobs:
  Hellow_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo Welcome to GitHub Actions
    
  
    
